workspacePath:
  kind: panel.input.text
  id: workspacePath
  name: workspacePath
  label: Workspace Path
  description: >
    The directory (as it appears to XNAT) containing user namespaced subdirectories (workspaces). JupyterHub is 
    responsible for mounting a user's workspace directory to the container running their Jupyter notebook server.

jupyterhubApiUrl:
  kind: panel.input.text
  id: jupyterHubApiUrl
  name: jupyterHubApiUrl
  label: JupyterHub API URL
  description: >
    The URL for the JupyterHub API

jupyterHubToken:
  kind: panel.input.password
  id: jupyterHubToken
  name: jupyterHubToken
  label: JupyterHub Token
  description: >
    The service token used by XNAT to launch a user's Jupyter Notebook Servers

startTimeout:
  kind: panel.input.number
  id: startTimeout
  name: startTimeout
  label: Start Timeout
  validation: integer gte:1 onblur
  description: >
    Timeout (in seconds) before giving up on starting of single-user server. XNAT will assume that startup has failed if it takes longer than this.

startPollingInterval:
  kind: panel.input.number
  id: startPollingInterval
  name: startPollingInterval
  label: Start Polling Interval
  validation: integer gte:1 onblur
  description: >
    The rate (in seconds) at which to poll JupyterHub to check if the single-user server has started.

stopTimeout:
  kind: panel.input.number
  id: stopTimeout
  name: stopTimeout
  label: Stop Timeout
  validation: integer gte:1 onblur
  description: >
    Timeout (in seconds) before giving up on stopping a single-user server. XNAT will assume that stopping has failed if it takes longer than this.

stopPollingInterval:
  kind: panel.input.number
  id: stopPollingInterval
  name: stopPollingInterval
  label: Stop Polling Interval
  validation: integer gte:1 onblur
  description: >
    The rate (in seconds) at which to poll JupyterHub to check if the single-user server has stopped.

pathTranslationXnatPrefix:
  kind: panel.input.text
  id: pathTranslationXnatPrefix
  name: pathTranslationXnatPrefix
  label: Path Translation XNAT Prefix
  description: >
    (Optional) Enter the XNAT_HOME server path, i.e. "/data/xnat"

pathTranslationDockerPrefix:
  kind: panel.input.text
  id: pathTranslationDockerPrefix
  name: pathTranslationDockerPrefix
  label: Path Translation Docker Prefix
  description: >
    (Optional) Enter the Docker Server path to the XNAT_HOME mount, i.e. "/docker/my-data/XNAT"

inactivityTimeout:
  kind: panel.input.number
  id: inactivityTimeout
  name: inactivityTimeout
  label: Inactivity Timeout (minutes)
  validation: integer gte:0 onblur
  description: >
    Automatically shut down idle Jupyter notebook servers if they've been inactive for some time. Set the timeout to 0 to not cull any inactive servers.

resourceSpecCpuLimit:
  kind: panel.input.number
  id: resourceSpecCpuLimit
  name: resourceSpecCpuLimit
  label: CPU Limit
  validation: decimal gte:0.0 onblur
  element:
    step: 0.1
  description: >
    (Optional) Maximum number of cpu-cores a single-user notebook server is allowed to use. If this value is set to 0.5,
    allows use of 50% of one CPU. If this value is set to 2, allows use of up to 2 CPUs. Set to 0 for this preference 
    to be ignored.

resourceSpecCpuReservation:
  kind: panel.input.number
  id: resourceSpecCpuReservation
  name: resourceSpecCpuReservation
  label: CPU Reservation
  validation: decimal gte:0.0 onblur
  element:
    step: 0.1
  description: >
    (Optional) Minimum number of cpu-cores a single-user notebook server is guaranteed to have available. If this value 
    is set to 0.5, allows use of 50% of one CPU. If this value is set to 2, allows use of up to 2 CPUs. Set to 0 for 
    this preference to be ignored.

resourceSpecMemLimit:
  kind: panel.input.text
  id: resourceSpecMemLimit
  name: resourceSpecMemLimit
  label: Memory Limit
  description: >
    (Optional) Maximum number of bytes a single-user notebook server is allowed to use. Leave this input empty for this
    preference to be ignored.
    Allows the following suffixes: 
      K -> Kilobytes
      M -> Megabytes
      G -> Gigabytes
      T -> Terabytes

resourceSpecMemReservation:
  kind: panel.input.text
  id: resourceSpecMemReservation
  name: resourceSpecMemReservation
  label: Memory Reservation
  description: >
    (Optional) Minimum number of bytes a single-user notebook server is guaranteed to have available. Leave this input 
    empty for this preference to be ignored.
    Allows the following suffixes: 
      K -> Kilobytes
      M -> Megabytes
      G -> Gigabytes
      T -> Terabytes

jupyterHubSetup:
  kind: panel
  name: jupyterHubSetup
  label: JupyterHub Setup
  contents:
    jupyterHubSetupTable:
      tag: "div#jupyterhub-setup-table"
    imagePreferencesScript:
      tag: script|src="~/scripts/xnat/plugin/jupyterhub/jupyterhub-hub.js"
    renderImagePreferencesTable:
      tag: script
      content: >
        XNAT.plugin.jupyterhub.hub.initSetupTable('jupyterhub-setup-table');

imagePreferences:
  kind: panel
  name: imagePreferences
  label: Images
  contents:
    imageDescription:
      tag: div.message
      contents:
        "This panel lists the containers which JupyterHub can use to launch single-user Jupyter notebook servers. JupyterHub supports any of the existing Jupyter docker stacks provided the version of JupyterHub in the image matches. Please see the documentation for building your own images. Pull each image on every swarm node."
    imagesTable:
      tag: "div#jupyterhub-image-preferences"
    imagePreferencesScript:
      tag: script|src="~/scripts/xnat/plugin/jupyterhub/jupyterhub-docker-images.js"
    renderImagePreferencesTable:
      tag: script
      content: >
        XNAT.plugin.jupyterhub.dockerImages.init('#jupyterhub-image-preferences');

jupyterhubPreferences:
  kind: panel.form
  name: jupyterhubPreferences
  label: JupyterHub Setup
  method: POST
  contentType: json
  url: /xapi/jupyterhub/preferences
  contents:
    ${jupyterhubApiUrl}
    ${jupyterHubToken}
    ${startTimeout}
    ${startPollingInterval}
    ${stopTimeout}
    ${stopPollingInterval}
    ${inactivityTimeout}
    ${pathTranslationXnatPrefix}
    ${pathTranslationDockerPrefix}
    ${workspacePath}
    ${resourceSpecCpuLimit}
    ${resourceSpecCpuReservation}
    ${resourceSpecMemLimit}
    ${resourceSpecMemReservation}

jupyterHubUserActivity:
  kind: panel
  name: jupyterHubUserActivity
  label: JupyterHub User Activity
  contents:
    jupyterHubActivityDescription:
      tag: div.message
      contents:
        "This panel lists all JupyterHub users and any Jupyter notebook servers they may be running."
    jupyterHubActivityTable:
      tag: "div#jupyterhub-user-activity-table"
    imagePreferencesScript:
      tag: script|src="~/scripts/xnat/plugin/jupyterhub/jupyterhub-users.js"
    renderImagePreferencesTable:
      tag: script
      content: >
        XNAT.plugin.jupyterhub.users.activity.init('jupyterhub-user-activity-table');

#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
  kind: tabs
  name: jupyerhubAdminPage
  label: JupyterHub Administration
  meta:
    tabGroups:
      jupyterhubTabGroup: JupyterHub
  contains: tabs
  tabs:
    jupyterhubPreferencesTab:
      kind: tab
      name: jupyterhubPreferencesTab
      label: Setup
      group: jupyterhubTabGroup
      active: true
      contents:
        ${jupyterHubSetup}
        ${imagePreferences}
    jupyterhubUserActivityTab:
      kind: tab
      name: jupyterhubUserActivityTab
      label: User Activity
      group: jupyterhubTabGroup
      active: true
      contents:
        ${jupyterHubUserActivity}