workspacePath:
  kind: panel.input.text
  id: workspacePath
  name: workspacePath
  label: Workspace Path
  description: >
    The directory (as it appears to XNAT) containing user namespaced subdirectories (workspaces). JupyterHub is 
    responsible for mounting a user's workspace directory to the container running their Jupyter notebook server.

jupyterhubApiUrl:
  kind: panel.input.text
  id: jupyterHubApiUrl
  name: jupyterHubApiUrl
  label: JupyterHub API URL
  description: >
    The URL for the JupyterHub API

jupyterHubToken:
  kind: panel.input.password
  id: jupyterHubToken
  name: jupyterHubToken
  label: JupyterHub Token
  description: >
    The service token used by XNAT to launch a user's Jupyter Notebook Servers

startTimeout:
  kind: panel.input.text
  id: startTimeout
  name: startTimeout
  label: Start Timeout
  description: >
    Timeout (in seconds) before giving up on starting of single-user server. XNAT will assume that startup has failed if it takes longer than this.

startPollingInterval:
  kind: panel.input.text
  id: startPollingInterval
  name: startPollingInterval
  label: Start Polling Interval
  description: >
    The rate (in seconds) at which to poll JupyterHub to check if the single-user server has started.

stopTimeout:
  kind: panel.input.text
  id: stopTimeout
  name: stopTimeout
  label: Stop Timeout
  description: >
    Timeout (in seconds) before giving up on stopping a single-user server. XNAT will assume that stopping has failed if it takes longer than this.

stopPollingInterval:
  kind: panel.input.text
  id: stopPollingInterval
  name: stopPollingInterval
  label: Stop Polling Interval
  description: >
    The rate (in seconds) at which to poll JupyterHub to check if the single-user server has stopped.

pathTranslationXnatPrefix:
  kind: panel.input.text
  id: pathTranslationXnatPrefix
  name: pathTranslationXnatPrefix
  label: Path Translation XNAT Prefix
  description: >
    (Optional) Enter the XNAT_HOME server path, i.e. "/data/xnat"

pathTranslationDockerPrefix:
  kind: panel.input.text
  id: pathTranslationDockerPrefix
  name: pathTranslationDockerPrefix
  label: Path Translation Docker Prefix
  description: >
    (Optional) Enter the Docker Server path to the XNAT_HOME mount, i.e. "/docker/my-data/XNAT"

jupyterhubPreferences:
  kind: panel.form
  name: jupyterhubPreferences
  label: Preferences
  method: POST
  contentType: json
  url: /xapi/jupyterhub/preferences
  contents:
    ${jupyterhubApiUrl}
    ${jupyterHubToken}
    ${startTimeout}
    ${startPollingInterval}
    ${stopTimeout}
    ${stopPollingInterval}
    ${pathTranslationXnatPrefix}
    ${pathTranslationDockerPrefix}
    ${workspacePath}


#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
  kind: tabs
  name: jupyerhubAdminPage
  label: JupyterHub Administration
  meta:
    tabGroups:
      jupyterhubTabGroup: JupyterHub
  contains: tabs
  tabs:
    jupyterhubPreferencesTab:
      kind: tab
      name: jupyterhubPreferencesTab
      label: Preferences
      group: jupyterhubTabGroup
      active: true
      contents:
        ${jupyterhubPreferences}