name: Release

on:
  push:
    tags:
        - 'v*.*.*'

jobs:

  release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: jdk

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.7

      - name: Build JAR with Gradle Wrapper
        run: ./gradlew clean jar

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
          body: The plugin JAR is attached to this release.
